import { Geist, Geist_Mono, Cairo } from "next/font/google";
import Navbar from "./componts/Navbar";
import Footer from "./componts/Footer";
import "./globals.css";
import "./styles/style.scss";

const geistSans = Geist({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} ${cairo.className} antialiased`}
        style={{ fontFamily: cairo.style?.fontFamily || "sans-serif" }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
